### ISSUE TITLE
插入导入失败

### ISSUE THREAD

**Issue by huzwu** [xiaotian2333/special-ability#2]
index.js 里面./plugins/Special-ability/apps

/Special-ability 是大写的，而其他地方都是小写。无法识别到S大写的文件夹。
建议 index.js 里面改成小写./plugins/special-ability/apps

**Comment by xiaotian2333** [comment]
这个问题似乎只在linux平台出现，开发插件用的是win平台所以未能发现此问题

涨教训了，不过目前没时间修改，需要等待周末有空才能改

**Comment by xiaotian2333** [comment]
已改为动态获取地址，现在随意改名都不会出现问题

但是由于本地列表的起始位置被修改，因此可能需要删除一次用户配置文件，在由插件默认生成
